import type { Metadata } from "next";
import { EB_Garamond, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const ebgaramon = EB_Garamond({
  variable: "--font-sans",
  subsets: ["latin", "vietnamese"],
  weight: ["400", "700"],
});

const ibmplexmono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["latin", "vietnamese"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebgaramon.variable} ${ibmplexmono.variable} antialiased`}
      >
        <div id="root">{children}</div>
      </body>
    </html>
  );
}
